### ISSUE TITLE
add layout/screen.css to repository

### ISSUE THREAD

**Issue by frog23** [bionoren/rssFilter#3]
in admin.php there is the css file `layout/screen.css` referenced, however it is not part of the repository. Probably because it just wasn't checked in. If there is a nicer styling for the admin interface, it would be worth putting it in the repository as well.

**Comment by bionoren** [comment]
No, there isn't :( I copied that template from another project, and missed the import. If you write something, I'll merge it in though :)

**Comment by frog23** [comment]
I guess I won't do it any time soon, as it has not much of a priority for me. But good to know. 
BTW I plan to do some other modifications which might be useful for others as well. So I wanted to ask, which style of pull request do you prefer: one request with several commits, each for one feature, or several pull requests, each for one feature on an separate branch?
Thanks for responding so quickly and thank you for this useful tool, and quite a good replacement for most of my pipes, now that Yahoo Pipes will be shutting down.
